version: "3.7"
services:
  postgresql:
    image: postgres:14
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: car_shop
      POSTGRES_USER: car_shop
      POSTGRES_PASSWORD: car_shop
    ports:
      - "5435:5432"
  nginx:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./app:/var/www/app
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./app:/var/www/app
    depends_on:
      - postgresql
    environment:
      DB_PORT: 5432
      DB_HOST: postgresql
  php-cli:
    build:
      context: ./docker
      dockerfile: ./php-cli/Dockerfile
    volumes:
      - ./app:/var/www/app
    depends_on:
      - postgresql
    environment:
      DB_PORT: 5432
      DB_HOST: postgresql
    tty: true